insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('H79', 'Greenlam', 'Cross-platform even-keeled application', 3, 1, null, '$32449.73');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('Z27', 'Keylex', 'Business-focused multimedia model', 3, 4, null, '$48264.68');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('P05', 'Cardguard', 'Advanced coherent service-desk', 4, 3, null, '$64540.21');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('E46', 'Y-Solowarm', 'Cross-group upward-trending benchmark', 2, 2, null, '$79779.35');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('K26', 'Prodder', 'Organic web-enabled hierarchy', 2, 2, null, '$94063.91');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('L71', 'Viva', 'Grass-roots background support', 2, 3, null, '$1662.42');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('X87', 'Asoka', 'Robust needs-based system engine', 4, 3, null, '$15001.13');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('L53', 'Otcom', 'Robust scalable open system', 4, 4, null, '$17763.51');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('O63', 'Daltfresh', 'Focused 24 hour adapter', 3, 1, null, '$8437.74');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('B79', 'Job', 'Cloned executive productivity', 2, 4, null, '$1638.89');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('X61', 'Fixflex', 'Organic real-time capability', 2, 4, null, '$76709.67');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('P12', 'Daltfresh', 'Multi-tiered responsive initiative', 2, 1, null, '$92107.51');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('A74', 'Stronghold', 'Virtual modular adapter', 1, 1, null, '$81456.45');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('A05', 'Transcof', 'Operative multi-state service-desk', 1, 2, null, '$47241.17');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('X49', 'Voltsillam', 'Seamless responsive knowledge base', 4, 1, null, '$62316.15');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('K64', 'Cookley', 'Universal logistical middleware', 3, 2, null, '$11590.60');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('R50', 'Bitwolf', 'Vision-oriented hybrid groupware', 5, 3, null, '$10533.19');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('H46', 'Voltsillam', 'Optional transitional forecast', 2, 3, null, '$41714.79');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('M18', 'Quo Lux', 'Diverse directional solution', 4, 3, null, '$58956.19');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('N15', 'Konklux', 'Progressive bottom-line intranet', 1, 3, null, '$88552.74');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('F83', 'Lotlux', 'Quality-focused foreground policy', 4, 3, null, '$38941.31');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('C56', 'Fintone', 'Intuitive methodical analyzer', 4, 4, null, '$23201.13');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('K79', 'Ventosanzap', 'Synergistic 24/7 model', 2, 1, null, '$23540.83');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('Z27', 'Quo Lux', 'Intuitive analyzing challenge', 4, 1, null, '$83560.69');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('Z72', 'Flexidy', 'Focused modular implementation', 2, 2, null, '$85799.46');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('W08', 'Stringtough', 'Managed attitude-oriented matrix', 4, 2, null, '$68984.59');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('X37', 'Stronghold', 'Team-oriented interactive monitoring', 2, 4, null, '$93641.78');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('A53', 'Alphazap', 'Re-contextualized asynchronous forecast', 2, 3, null, '$73834.53');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('X56', 'Treeflex', 'Expanded 24 hour superstructure', 2, 1, null, '$35710.62');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('J76', 'Tampflex', 'Extended holistic productivity', 3, 4, null, '$59079.22');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('H32', 'Andalax', 'Enterprise-wide composite workforce', 4, 1, null, '$36324.26');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('V16', 'Prodder', 'Implemented object-oriented superstructure', 3, 1, null, '$90999.92');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('E33', 'Mat Lam Tam', 'Triple-buffered impactful utilisation', 5, 1, null, '$10512.17');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('P74', 'Veribet', 'De-engineered attitude-oriented matrices', 5, 1, null, '$95343.60');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('O72', 'Matsoft', 'Synergistic background application', 3, 3, null, '$39270.92');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('Y21', 'Tin', 'Upgradable clear-thinking contingency', 4, 4, null, '$33469.07');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('X08', 'Bytecard', 'Streamlined heuristic task-force', 3, 2, null, '$31021.26');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('U22', 'Subin', 'Visionary motivating task-force', 1, 2, null, '$20986.64');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('I09', 'Hatity', 'Diverse asymmetric capacity', 1, 1, null, '$63910.72');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('A17', 'Alphazap', 'Mandatory directional productivity', 3, 3, null, '$82579.58');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('B22', 'Solarbreeze', 'Persistent uniform protocol', 4, 4, null, '$73075.89');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('I80', 'Ronstring', 'Horizontal clear-thinking artificial intelligence', 5, 1, null, '$89805.45');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('L74', 'Y-find', 'Compatible background projection', 5, 4, null, '$893.73');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('Q68', 'Alphazap', 'Object-based 24/7 website', 2, 3, null, '$84818.92');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('D02', 'Ronstring', 'Synergistic client-driven benchmark', 1, 4, null, '$59092.30');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('G24', 'Daltfresh', 'Synergized multimedia infrastructure', 3, 2, null, '$35966.54');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('J34', 'Ronstring', 'Organized radical installation', 2, 4, null, '$77987.94');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('M01', 'Tresom', 'Team-oriented 5th generation artificial intelligence', 1, 2, null, '$8761.99');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('T22', 'Regrant', 'Operative zero administration model', 2, 2, null, '$52235.31');
insert into ARTICULOS (Codigo, Nombre, Descripcion, IdMarca, IdCategoria, ImagenUrl, Precio) values ('I38', 'Mat Lam Tam', 'Devolved disintermediate software', 5, 2, null, '$52426.91');
